apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs  
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodongo
        image: heroku/nodejs-hello-world
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-deployment
  labels:
    service: nodejs
spec:
  ports:
  - port: 3000
    name: client
  selector:
    app: nodejs

